[package]
name = "babyjubjub-rs"
version = "0.0.8"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"
license = "GPL-3.0"
description = "BabyJubJub elliptic curve implementation"
repository = "https://github.com/arnaucube/babyjubjub-rs"
readme = "README.md"

[dependencies]
ff = {package="ff_ce" , version="0.13", features = ["derive"]}
rand = "0.8"
num = "0.4.0"
num-bigint = {version = "0.4.0", features = ["rand"]}
num-traits = "0.2.8"
blake-hash = {version="0.4.0", optional=true}
blake = {version="2.0.1", optional=true}
generic-array = "0.14.4"
tiny-keccak = "1.5"
rustc-hex = "1.0.0"
poseidon-rs = "0.0.8"
arrayref = "0.3.5"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_babyjubjub"
harness = false

[features]
default = ["blake-hash"]
aarch64 = ["blake"]

[patch.crates-io]
poseidon-rs = { git = "https://github.com/Fluidex/poseidon-rs.git" }
ff = { package = "ff_ce", git = "https://github.com/Fluidex/ff.git", branch = "serde" }